/**
 * Prototype / pseudocode representation of API item representations which could be generated by the analysis tooling.
 *
 * Loosely based on `@microsoft/api-extractor` concepts.
 * I think their hierarchical representation is nice, and would be useful to emulate.
 * But they have type-safety gaps that I think we can improve on.
 * And their representation is stateful and leverages classes.
 * We should aim for a type-safe, hierarchical, and stateless representation using interfaces.
 */

// TODO: rename this module to "apiModel.ts"

// TODO: ensure we have a format versioning system for the API model.
// Otherwise, we will have difficulty managing changes to the API model over time.

/**
 * The name of a package.
 * @remarks Must be unique within the suite.
 * @privateRemarks
 * TODO: this probably belongs somewhere else. This could be re-used across the package.
 * TODO: consider using a well-defined regex for package names.
 * TODO: consider using a branded type for stronger type safety.
 */
export type PackageName = string;

/**
 * A unique identifier for an API item within the scope of a package.
 * @remarks This identifier is only unique within the context of the package it belongs to.
 * @privateRemarks
 * TODO: consider using stronger typing for the local API identifier.
 * It would likely make sense to just use TSDoc's selector syntax for this, rather than inventing a new format.
 * TODO: consider using a branded type for stronger type safety.
 */
export type LocalApiIdentifier = string;

/**
 * A unique identifier for an API item across all packages in the suite.
 * @privateRemarks
 * TODO: consider using stronger typing for the local API identifier.
 * It would likely make sense to just use TSDoc's selector syntax for this, rather than inventing a new format.
 * TODO: consider using a branded type for stronger type safety.
 */
export type ApiIdentifier = `${string}#${LocalApiIdentifier}`;

/**
 * Represents the overall structure of the API surface for a package.
 */
export interface ApiPackageModel {
  // TODO: need to think on this setup more. I don't think this is the right setup.
  // It might make more sense to have a single record of exports, and have parsed items track their canonical source.

  /**
   * APIs exported by this package.
   * @remarks Only includes exports of items defined within this package.
   */
  readonly localExports: Readonly<Record<LocalApiIdentifier, ApiItem>>;

  /**
   * APIs re-exported from external packages.
   */
  readonly reExports: Readonly<Record<ApiIdentifier, ApiItem>>;
}

/**
 * Documentation on an API item.
 */
interface ApiDocumentation {
  // TODO: we probably want to store a serializable form of the parsed comment, rather than just the raw string.
  // If TSDoc offers a way to serialize the parsed comment, we should use that.
  // Otherwise, we may need to consider adding our own serialized representation.
  readonly docComment: string;

  // Possibly other derived metadata that's useful to the system?
  // Question: what would users need? Or should we just let them (and the system) derive metadata as needed?
}

/**
 * The kind of API item.
 */
export enum ApiItemKind {
  CallSignature = "CallSignature",
  Class = "Class",
  Constructor = "Constructor",
  ConstructSignature = "ConstructSignature",
  EntryPoint = "EntryPoint",
  Enum = "Enum",
  EnumMember = "EnumMember",
  Function = "Function",
  IndexSignature = "IndexSignature",
  Interface = "Interface",
  Method = "Method",
  MethodSignature = "MethodSignature",
  Model = "Model",
  Namespace = "Namespace",
  Package = "Package",
  Property = "Property",
  PropertySignature = "PropertySignature",
  TypeAlias = "TypeAlias",
  Variable = "Variable",
}

/**
 * An API item.
 * @remarks
 * Separate overloads of functions or methods are represented as distinct API items.
 */
export interface ApiItem<TKind extends ApiItemKind = ApiItemKind> {
  readonly kind: TKind;
  readonly documentation?: ApiDocumentation;

  /**
   * The containing context for this API item, if any (e.g., the class containing a method), by ID.
   * @privateRemarks
   * TODO: do we need a potentially cross-package identifier here? Or will a local identifier suffice? Is it possible (via merged declarations across package boundaries, for example) to have a parent context that is not local to the current package?
   */
  readonly parent?: ApiIdentifier;

  // Other data common to all kinds of API items
}

/**
 * An API item with child elements
 */
export interface ApiParentItem<
  TKind extends ApiItemKind = ApiItemKind,
> extends ApiItem<TKind> {
  /**
   * The child elements of this API item, by ID.
   */
  readonly children: readonly ApiIdentifier[];
}

// TODO: probably a type that represents API items may have child elements
// Child elements should be type-restricted based on the kind of API item they belong to.

// TODO: specific types can constrain the types of child elements they can have and the types of parent contexts they can appear in.

/**
 * API item representing a package.
 *
 * @remarks
 * May contain 1 or more entrypoints.
 * The documentation for the package comes from the `@packageDocumentation` comment.
 */
export interface ApiPackage extends ApiParentItem<ApiItemKind.Package> {
  readonly entrypoints: readonly ApiIdentifier[];
}

/**
 * API item representing a function.
 */
export interface ApiFunction extends ApiItem<ApiItemKind.Function> {
  // Function-specific data (parameters, etc.)
}

// ...
