import type { DocComment } from "@microsoft/tsdoc";

/**
 * Prototype / pseudocode representation of API item representations which could be generated by the analysis tooling.
 *
 * Loosely based on `@microsoft/api-extractor` concepts.
 * I think their hierarchical representation is nice, and would be useful to emulate.
 * But they have type-safety gaps that I think we can improve on.
 * And their representation is stateful and leverages classes.
 * We should aim for a type-safe, hierarchical, and stateless representation using interfaces.
 */

/**
 * Documentation on an API item.
 */
interface ApiDocumentation {
	readonly parsedComment: DocComment;

	// Possibly other derived metadata that's useful to the system?
	// Question: what would users need? Or should we just let them (and the system) derive metadata as needed?
}

enum ApiItemKind {
	Accessor,
	CallSignature,
	Class,
	ConstructSignature,
	Constructor,
	Enum,
	Event,
	Function,
	Interface,
	IndexSignature,
	Method,
	Module,
	Namespace,
	Package,
	Parameter,
	Property,
	TypeParameter,
	TypeAlias,
	Variable,

	// TODO: did I miss anything?
}

/**
 * An API item.
 * @remarks
 * Separate overloads of functions or methods are represented as distinct API items.
 */
export interface ApiItem<
	TKind extends ApiItemKind = ApiItemKind,
	TParent extends ApiItem | undefined = undefined,
> {
	readonly kind: TKind;
	readonly documentation?: ApiDocumentation;

	/**
	 * The containing context for this API item, if any (e.g., the class containing a method).
	 */
	readonly parentContext?: TParent;

	// Other data common to all kinds of API items
}

/**
 * An API item with child elements
 */
export interface ApiParentItem<
	TKind extends ApiItemKind = ApiItemKind,
	TChild extends ApiItem = ApiItem,
	TParent extends ApiItem | undefined = undefined,
> extends ApiItem<TKind, TParent> {
	readonly children: readonly TChild[];
}

// TODO: probably a type that represents API items may have child elements
// Child elements should be type-restricted based on the kind of API item they belong to.

// TODO: specific types can constrain the types of child elements they can have and the types of parent contexts they can appear in.

/**
 * API item representing a package.
 * @remarks May contain 1 or more entrypoints.
 */
export interface ApiPackage extends ApiParentItem<ApiItemKind.Package> {
	// The docs for the package come from the `@packageDocumentation` comment.
	// Package-specific data (entrypoints)
}

/**
 * API item representing a function.
 */
export interface ApiFunction extends ApiItem<ApiItemKind.Function> {
	// Function-specific data (parameters, etc.)
}

// ...
